# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Happy moments
tagline:          'Nick Luo site'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://nick32m.github.io/funs

author:
  name:           'Nick Luo'
  url:            https://twitter.com/nick32m

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nick32m/funs


baseurl:          /funs
